### PR TITLE
UGC-1044 | Fix sync issues when removing or pasting text on GBoard

### PR DESCRIPTION
**Pull request by MrVanosh**
https://github.com/Wikia/unified-platform/pull/15554
https://fandom.atlassian.net/browse/UGC-1044

### CODE REVIEW

**Review by mszabo-wikia — COMMENTED** [review]
How does this behave on non-GBoard inputs?

**Comment by MrVanosh** [comment]
@mszabo-wikia I've checked that on Samsung and Hacker's keyboard and I didn't see any difference as on them mobile editor is working without any issues and I've not observed that changed after those changes.

**Comment by mszabo-wikia** [comment]
What about desktop?

**Comment by MrVanosh** [comment]
> What about desktop?

Will look into it.

**Comment by MrVanosh** [comment]
@mszabo-wikia Checked on desktop and removing, pasting, typing etc. looks fine beside removing being kinda laggy with syntax higlighting turned on (But it is same without those changes). Of course I'm checking if edit matches state that will be saved.

**Review by mszabo-wikia — APPROVED** [review]

**Review by kasperekt — APPROVED** [review]

**Pull request merged**
